import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/header";
import Hero from "@/app/components/home/hero";
import Shop from "@/app/components/shop/page";
import Blog from "@/app/components/blog/page";
import Contact from "@/app/components/contact/contactPage";
import Footer from "@/app/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <Header />
       <Hero />
       <Shop />
       <Blog />
       <Contact />
        {children}
        <Footer />
      </body>
    </html>
  );
}
